### ISSUE TITLE
Why are the models in the checkpoint folder?

### ISSUE THREAD

**Issue by jdc4429** [kijai/ComfyUI-SUPIR#147]
Why are the models in the checkpoint folder? They should be in the upscaling folder...

**Comment by kijai** [comment]
Because it's a diffusion model, comfy default upscaling folder is for upscaling models, and this wouldn't work with nodes using those anyway. SUPIR is a combination of unet and controlnet,there's no good default folder so I initially just chose checkpoints. Changing it at this point would just cause lots of confusion with existing setups.
