### ISSUE TITLE
Upscaled image has a different width:height ratio than original image

### ISSUE THREAD

**Issue by dietrichr022** [kijai/ComfyUI-SUPIR#28]
I've noticed that on certain images the upscaled image has a different ratio than the original one so that the resulting image looks very slightly stretched.

It has happened when upscaling an image of size 696x768 by 2x. The resulting image size is 1344x1536, which has less width than 2x696 so that the image looks vertically stretched. I can tell it is not cropping the resulting image but just making it narrower. So far it has only happened with the width of the image; it has never happened with the height.

**Comment by cdb-boop** [comment]
**Either manually or with a custom node, you need to crop or pad the image so that, after being multiplied with `scale_by`, each dimension is divisible by 64.**

This is because the code is currently hard-coded to round down to the nearest multiple of 64.

```python
image, = ImageScaleBy.upscale(self, image, resize_method, scale_by)
B, H, W, C = image.shape
new_height = H // 64 * 64
new_width = W // 64 * 64
```

696 is not a multiple of 64 and so it gets scaled like this:

1. `696 * 2 = 1392`
2. `1392 / 64 = 21.75`
3. `floor(21.75) = 21`
4. `21 * 64 = 1344`

**Comment by kijai** [comment]
It should be scaled back as of few days ago when I first noticed this, are you sure you're on latest version?

**Comment by dietrichr022** [comment]
> It should be scaled back as of few days ago when I first noticed this, are you sure you're on latest version?

Well, now I am and I am not experiencing the stretching any more. Thanks!
