### ISSUE TITLE
custom vae choice, the default sdxl vae has invisible-watermark

### ISSUE THREAD

**Issue by CuddleSabe** [kijai/ComfyUI-SUPIR#31]
custom vae choice, the default sdxl vae has invisible-watermark

**Comment by brentjohnston** [comment]
Yeah it also creates white orbs issue if you use any juggernaut v9 merged at all with any other models (because of their baked in vae). To fix this I would always use the fp16 vae fix, but it doesn't seem to select that here.

Superir gives much better results for the likeness when upscaling with the subject dreambooth trained first, (even when using blurry photos and some clear ones mix in the dataset) tested.

**Comment by brentjohnston** [comment]
I found a workaround fix.

```
1. Go to Checkpoint merger tab.
2. Load your model from the "Primary model (A)" dropdown.
3. Set a name (Optional)
4. Slide the "Multiplier (M)" slider to: 0
5. Under "Interpolation Method" select: No interpolation
6. Enable: Save as float16 if needed
7. The default option for a "Bake in VAE" is: None (Leave it or select the fp16 vae fix)
8. Click the "Merge"
```

**Comment by kijai** [comment]
Finally figured this out and it was very simple, you can now use comfy model loader:
![image](https://github.com/kijai/ComfyUI-SUPIR/assets/40791699/25187e53-c46e-42b2-ac5b-26d4657fc1fb)
