### ISSUE TITLE
Separation of Stages?

### ISSUE THREAD

**Issue by caniyabanci76** [kijai/ComfyUI-SUPIR#48]
In the original SUPIR repo demo there are two stages.  stage 1 being that it seems to just soften the low-res image in preparation before the actual restore / upscale pass.  If the original image is of sufficient image quality, then this stage can be skipped. Is this available in this node implementation?

**Comment by kijai** [comment]
Not yet, it's planned as the separation is needed also for other stuff, like per-tile captioning for larger tiled upscales. Also the node is growing uncomfortably large. I was hoping someone would figure out how to use the controlnet portion of this on it's own on comfy so that we wouldn't need clumsy wrapper node, it feels very backwards to work in a whole diffusion pipeline within comfy that already has far more advanced one.

**Comment by kijai** [comment]
Looked at the gradio code again, what it calls "stage2" actually does do the stage1 internally as well. They just have option to run stage1 only for llava. I tried skipping that and results are mostly terrible, but I have separated lot of the process already (in dev branch currently) so we can use other methods to clean up the image instead, or not at all if it's good enough like you said.

**Comment by kijai** [comment]
For what it's worth, this is now done. Results absolutely depend on the initial image though, preprocessing could be done with another node besides the first stage too.
