### ISSUE TITLE
Image Resolution Must Be Divisible by 64?

### ISSUE THREAD

**Issue by camoody1** [kijai/ComfyUI-SUPIR#69]
First, I want to say that this new version of SUPIR is producing a FAR better output image than the last. Well done! Good work and thank you.

I was just working with an image that is sized 736x504. I attempted to double the size of it to 1472x1008. Every time I ran the workflow, however, the resulting image would come out 1472x960. This made the image appear "squished". It became clear after some more testing that this engine seems to require your resulting image to be divisible by 64. When I cropped my starting image to be 736x480 and then attempted a 2x upscale, the upscale came out perfect at 1472x960. What is happening here? Why is there this odd requirement? Is there any way to remove that requirement?

**Comment by kijai** [comment]
Yeah it's forced to round it to be dividable as otherwise it just errors out, I don't know how it's handled in other diffusion codebases that seem to allow any resolution inputs. Previously in the single node I was simply scaling it back at the end, but I don't know how to do that when the process divided to multiple nodes as I can't reference the original size. It's simple enough to do with other nodes though.

**Comment by kijai** [comment]
It does look like 32 is enough, 16 or 8 did not work. I checked how comfy does it and it simply crops it to nearest dividable by 8, and it's just never scaled back. So even basic img2img workflow in comfy will have different dimensions as end result in a case it's not dividable by 8.

 I'm working on automating it, but doing it manually is always best so there's no surprises.

**Comment by camoody1** [comment]
@mocmocmoc This is a great workflow to get the job done. I sure wish it wasn't necessary, though. That's a lot of nodes for something that seems to "just work" in every other process I've ever run.

**Comment by kijai** [comment]
> @mocmocmoc This is a great workflow to get the job done. I sure wish it wasn't necessary, though. That's a lot of nodes for something that seems to "just work" in every other process I've ever run.

I have now changed the automatic resizing to 32 instead of 64 as it seems to work, and I'm passing the original size from the encoder to the conditioner to the sampler to the decoder, which then resizes it back to the original.

If this is not desirable, to avoid this altogether you only have to make sure the input is dividable by 32 before encoding.

**Comment by camoody1** [comment]
Thank you for your work. I'll go ahead and close this issue.
